var testi =["He dejado, despues de casi dos años, mi trabajo como pizzero para dedicarme completamente al estudio",
  "Primer dia de universidad en la facultad de 'Comunicación digital'",
  "Mi primer viaje solo: vuelta de Italia en tren<br/>En este viaje volveré a encontrar amigos que viven en la ciudades de Bergamo, Venecia y Roma",
  "Finalmente recibo la carta de exonero del servicio militar.<br/>Decido que en septiembre empezaré la universidad.",
  "Trabajo como 'Glass collector' en un pub en la periferia de Londres, cerca de donde vivía.",
  "Acabo el primer año de universidad con 6 de 8 asignaturas aprobadas<br/><br/>Consiguo la Certificación FSE Microsoft 2000 server en un curso patrocinado por el Fondo Social Europeo.",
  "Mi primer viaje en avión. Destino:Londres!Decido pasar allí parte del verano para trabajar y mejorar mi nivel de inglés.",
  "A los pocos dias de haber vuelto de Londres se presenta la ocasión de un fin de semana largo en Amsterdam.",
  "Segunda vuelta de Italia en tren.<br/>Esta vez el tour toca Roma, Palermo, Agrigento,Molinara (Benevento),Turín.<br/>A lo largo de este viaje encontraré algunos amigos conocidos poco tiempo antes en Londres.",
  "Consiguo el carnet de conducir",
  "Trabajo como cocinero en un club del centro de Milán preparando aperitivos y bocatas para el 'Happy hour'",
  "Frecuento por la tarde un Curso de Formación CISCO, de seis meses. A su conclusión consiguo el CCNA (Cisco Certified Networking Associated)",
  "Certificación FSE Flash Mx<br/><br/>Certificación FSE Sound Forge 6.0",
  "Certificación FSE Photoshop 7.0",
  "Certificación FSE Illustrator 10",
  "Certificación FSE Maya 5.0<br/><br/>30/05 - Recibo la beca Erasmus para un semestre en el BTU de Cottbus (Alemania)",
  "Visito San Sebastian en la semana granda.",
  "02/10 - Viaje de sola ida con destino Cottbus",
  "Vuelo de vuelta a Italia para navidades",
  "Conozco a Carmen, a los pocos dias, el 29/05, empezaremos en estar juntos. <br/>",
  "Carmen vuelve a Italia despues del verano en España<br/>Contra toda previsón volvemos a estar juntos.",
  "Encuentro trabajo como gestor de la bocatería: 'Piadineria la Caveja'. Seguiré con ese oficio hasta el verano 2006",
  "Antes de volver a Alemania, despues de las navidades, vuelo por la primera vez a España, hacia Valencia.",
  "Desde Berlin me voy una semana a Valencia para las Fallas.<br/><br/>Vuelo de vuelta desde Berlin a Milán. Mi Erasmus ha concluido.",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Carmen y yo alquilamos una casa para un mes en el barrio de Na Jordana, en Valencia.<br/>Es nuestra primera convivencia.",
  "La bocateria cierra por vacaciones",
  "Vuelta al trabajo",
  "Volo de ida para Valencia",
  "Carmen yo hacemos nuestro primero viaje juntos.<br/>En autobus recorremos España en visita a varios amigos en todo el pais.<br/>En 15 dias visitaremos, Valladolid,La Coruña, Santiago de Compostela y Salamanca",
  "Volo de vuelta a Italia",
  "Como el año anterior Carmen y yo alquilamos una casa en Valencia para pasar todo el verano juntos.",
  "Carmen y yo celebramos nuestra primera nochevieja juntos en Como.",
  "Después de dos años como gestor, dejo el trabajo en la bocatería para dedicarme al proyecto de fin de carrera",
  "Diploma en 'comunicación digital'",
  "Curso de formación sobre: <br/>Tecnología COM: VB6.0, ADO, ASP, Sql.<br/>Tecnología .NET 2.0: C#2.0, VisualStudio 2005, ADO.NET, ASPX. (300h)",
  "MXP - VLC a/r: Albarracín?",
  "Una semana antes de la ceremonia de entrega de los diplomas voy a visitar Carmen que está en Estocolmo por trabajo.<br/>Después de la entrega del diploma voy un finde a Amsterdam con los amigos para celebrar la conclusión de una epoca importante de mi vida.",
  "Vuelvo a Suecia para estar con Carmen casi 3 semanas. Juntos visitaremos Estocolmo y Linköping.",
  "Viaje de vuelta desde Estocolmo",
  "Ganador de un concurso de desarrollo de páginas web convocado por la fundación 'Ferrario' para el rediseño del portal de los servicios para los ancianos.",
  "Celebro la nochevieja junto a Carmen y mis amigos en Milán",
  "Comienza mi trabajo para Nexus Advanced Tecnologies.<br/>Inicialmente como trabajador interno a la empresa y después como consultor de desarrollo web empleado en el banco Fineco de Milán.",
  "Mi primero proyecto como freelancer: Omniamarmi. Una pagina web para un artesán del marmól.",
  "Segundo trabajo como freelancer: Gilgamesh lounge bar.",
  "Conclusión del curso en tecnologías COM y .NET. <br/>De los partecipantes,4 serán contratados por una empresa de desarrollo software llamada Nexus advanced technologies.",
  "MXP - VLC a/r",
  "MXP - VLC a/r",
  "Acompaño Carmen a Norköping (Suecia) para un ciclo de conferencias acerca del proyecto que llevó el año anterior.",
  "MXP - VLC a/r 2x",
  "MXP - VLC a/r 2x",
  "Carmen y yo, por la primera vez, podemos visitar la obra donde surgirá nuestra nueva futura casa.",
  "Nochevieja en Milán a solas Carmen y yo.",
  "Tercer trabajo como freelancer. Excalibur: web mas foro para una tienda de maquetas y juegos de rol.",
  "Cuarto trabajo como freelancer. Web para el restaurante 'Rebelot'",
  "Dejo mi trabajo en Nexus",
  "Mi primer trabajo en España. Desarrollador web para una pequeña empresa en Manises: Alerce",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "Viaje de sola ida para VLC",
  "VLC - MXP a/r",
  "VLC - MXP a/r",
  "Viaje a Milán par celebrar las navidades, junto con Carmen,  con mi familia",
  "19 AGOSTO - Después de 5 años separado, finalmente llega el día de dejar Italia y irme a vivir junto con Carmen en Valencia.",
  "Nochevieja en Italia",
  "Dejo el trabajo en Alerce para otra empresa de desarrollo web: Aitana multimedia",
  "Curso de actualización sobre la versión 3.5 del framework .NET.",
  "Viaje a italia",
  "Viaje a italia",
  "Viaje a italia",
  "Escapadita en Frankfurt",
  "Viaje a italia",
  "30 diciembre - Compro mi primer coche un Ford Fiesta de segunda mano.",
  "Causa crisis la empresa donde trabajo tiene que hacer recortes y por esto pierdo mi puesto de trabajo",
  "El Instituto tecnologico de la madera y mueble de Paterna me ofrece una colaboración para maquetar los contenidos web de su aula virtual",
  "13 April - Contrato indefinido como programador junior en ZED WORLDWIDE",
  "Por un proyecto Europeo Carmen tiene que ir a Finlandia unos dias. Me voy con ella y juntos visitamos Helsinki",
  "Como regalo de compleaño, complotando con su novio, regalo a mi hermana un viaje a Rumania. Juntos visitaremos el castillo de Bran.",
  "Italia",
  "Praga",
  "La joyera 'De la Concepción' de Valencia, realiza, según mi diseño, mi anillo de pedida",
  "12 octubre - En Praga, al atardecer, en la orilla del rio Moldava pido a Carmen de casarse conmigo.",
  "Acompaño Carmen en Milán para la feria de mueble.",
  "Italia para la boda de un amigo",
  "Escapadita a Escocia",
  "19 noviembre - Carmen y yo, despues de mas de 8 años de noviazgo, nos casaremos.",
  "Viaje de novios a Australia.",
  "Fin de semana largo en Andalucía, Carmen y yo visitaremos Malaga y Granada.",
  "Dejo mi trabajo en ZED WORLDWIDE para participar a la creación de JUGO: una startup de la empresa CANALES CORPORATIVOS",
  "Nuevo trabajo como freelancer: web corporativa de <b><a href='http://www.madeinnovation.es' target='_blank'>Madeinnovation</a></b> : un estudio de asesores de gestión de la producción industrial.",
  "Causa incompatibilidad entre mi perfil profesional y las necesidades de la empresa, mi colaboración con CANALES CORPORATIVOS se interrumpe."
];
$(function() {
		$( "#slider" ).slider({
			value:2012,
			min: 2001,
			max: 2012,
			step: 1,
			slide: function( event, ui ) {
				$( "#year" ).val(ui.value);
        changeyear(ui.value);
			}
		});
		$( "#year" ).val( $( "#slider" ).slider( "value" ) );
    changeyear($("#slider").slider("value"));
	});
function changeyear(val){
  $(".anno").css("display","none");
  $("#"+val).css("display","block");
  $('#evento').fadeOut('400',function (){$('#evento').html("")});
}
function testo(i){
    $('#evento').fadeOut('400',function (){$('#evento').html(testi[i]);$('#evento').fadeIn('400');});
}
