
var testi =["After 21 months I left my work as pizza chef in order to complete my studies",
  "First day at the Digital Comunication's faculty of the Milan University",
  "My first trip myself: italian tour by train<br/>In this travel I'll meet again some friends who were living in the cities of Bergamo, Venice and Rome.",
  "Finally I am exonerated to the military service.<br/>I choose to start te university in September.",
  "I work as 'Glass collector' in a pub in the suburb of London, near my home.",
  "I finished my first year at the university with 6 of 8 approved exams<br/><br/>I get the ESF Microsoft 2000 server certification in a course sponsored by the European Social Found.",
  "My first flight. Destination: London! I choose to spend there the summer to work and improve my English.",
  "Few days later coming back from London an opportunity shows up to go to Amsterdam for a long weekend",
  "Second trip trought Italy<br/>This time the tour reach Rome, Palermo, Agrigento,Molinara (Benevento),Turín.<br/>In the course of this travel I will encounter some friends who I met in London few weeks before.",
  "I got my the driving license",
  "I work as chef in a club in the center of Milan preparing aperitif, cocktails and snack for the 'Happy hour'",
  "I completed an evening CISCO training course (6 months) and achieved the CCNA (Cisco Certified Networking Associated)",
  "ESF Flash Mx certification<br/><br/>ESF Sound Forge 6.0 certification",
  "ESF Photoshop 7.0 certification",
  "ESF Illustrator 10 certification",
  "ESF Maya 5.0 certification<br/><br/>30/05 - I got an Erasmus grant at BTU, Cottbus (Germany)",
  "I visited San Sebastian for the 'semana granda'",
  "02/10 one vay trip to Cottbus",
  "I came back to Italy form Christmas holydays",
  "I meet a spanish girl, Carmen, few days later (29/05)we start our relationship.<br/>",
  "Carmen came back to Italy after spending the summer in Spain<br/>Against all guesses our relationship didn't break",
  "I find a new job: administrator of the sandwich-bar 'Piadineria la Caveja' in Milán. I'll work there until summer 2006",
  "Before coming back from Germany, after Christmas, I flew for my first time to Valencia.",
  "From Berlin I go to Valencia to spend there one week to see the city on Fallas: the city carnival.<br/><br/>Fly back to Milán; my Erasmus ends.",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Carmen and I rent a home for one mont in 'Na Jordana' distric, in Valencia.<br/>This was our first time living together",
  "My snack bar close for holydays" ,
  "Back to the work",
  "One vay flight to Valencia",
  "Carmen and I had ouur first journey together.<br/>By bus we cross Spain to meet some friends linving all over the country.<br/>In 15 days we visit: Valladolid,La Coruña, Santiago de Compostela and Salamanca",
  "Flight back to Italy",
  "As the year before, Carmen and I rent a home to spend together all the summer in Valencia." ,
"Carmen and I celebrate our first New Year's Eve together in Como." ,
"After two years as administrator, I left my work in the sandwich bar in order to complete my bachelor's thesis",
"Bachelor in 'Digital Communication'",
"Training course about:<br/>COM Tecnology: VB6.0, ADO, ASP, Sql. (150h)<br/>NET Tecnology 2.0: C#2.0, VisualStudio 2005, ADO.NET, ASPX. (300h)",
"MXP - VLC and return. Little trip to Albarracín",  
"One week before the graduation ceremony I went to Stockholm to meet Carmen for a couple of days, who is there to work.<br/><br/>After the graduation ceremony I went to Amsterdam with my friends to celebrate the end of one of the most important eras of my life.",
"I went back to Sweden to meet Carmen again, but this time I stayed there 3 weeks. Together we visited Stockholm an Linköping.",
"Flight back from Stockholm.",
"1st prize in a web development contest organized by 'Ferrario' foundation, consisting in a complete portal of services for elderly people.",
"I celebrated the new Year's Eve with Carmen and my friends in Milán.",
"I start to work for Nexus Advanced Tecnologies.<br/>For my firsts six months I was internal developer and after I became external web developer consultant for Fineco Bank in Milán.",
"My first proyect as freelance: Omniamarmi. A web page for a marble artist.",
"Second proyect as freelance: Gilgamesh lounge bar.",
"End of the training about COM and .NET technologies. <br/>Four of us, will be recruited by a software house called Nexus Advanced Technologies.",
  "MXP - VLC a/r",
  "MXP - VLC a/r",
  "I went with Carmen to Norköping (Sweden)for a conference about the project she developed the year before.",
  "MXP - VLC a/r 2x",
  "MXP - VLC a/r 2x",
  "Carmen and I, for the first time, went to see the buildig site where our future home will surge.",
"Romantic New Year's Eve at Milan, only Carmen and I.", 
"Third work as freelance: Excalibur. A web page with forum for a fantasy shop.",
"Fourth work as freelance. Webpage for the restaurant 'Rebelot'.",
"I left my work at Nexus.",
"My first work in Spain. Web developer for a little web studio in Manises:Alerce.",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "On way flight to Valencia",
  "VLC - MXP a/r",
  "VLC - MXP a/r",
  "Trip to Milan to celebrate the Christmas holydays with Carmen and my family.",
  "19 AUGUST - After 5 years of distance, finally, comes the day to leave Italy and to go to live with Carmen in Valencia.",
  "New Year's Eve in Italy.",
  "I left my work at Alerce for a bigger web studio: Aitana multimedia.",
  "Actualization course about the 3.5 version of .NET framework.",
  "Trip to Italy.",
  "Trip to Italy.",
  "Trip to Italy.",
  "Weekend at Frankfurt.",
  "Trip to Italy.",
  "30 december - I bought my first car: a second hand Ford Fiesta.",
  "Cause crisis I'm dismissed from work.",
"The training department of AIDIMA, (the technological institute of wood, furniture, and packaging) called me to develope the contents of the online training courses.",
"13 April - Open end contract of employment as junior programmer at ZED WORLDWIDE.",
"For an European proyect, Carmen had to go to Finland for a week. I went with her and together we visited Helsinki.",
"As a birthday present, conspiring with her boyfriend, I gift to my sister a week in Romania. Together we visited the famous Bran castle.",
  "Trip to Italy.",  
  "8 days trip to Praga.",
"The jeweler 'De la Concepción', build, following my design, my engagement ring." , 
"12 octuber - In Prague, at sunset on the Moldava's riverside I ask to Carmen to marry me.", 
"I accompanied Carmen to Milan for the furniture exhibition.",
"Carmen and I went to Italy for a friend marriage.",
"Summer holydays in Scotland.",
"19 November - Carmen and I, after 8 years of engagement, got married.",
"Honeymoon in Australia.",
"Long weekend in Andalucía, Carmen and I visited Malaga y Granada.",
"I leaved in ZED WORLDWIDE to participate in the creation of JUGO: a startup of CANALES CORPORATIVOS",
"New work as freelance: corporative wev of <b><a href='http://www.madeinnovation.es' target='_blank'>Madeinnovation</a></b> : a R&D of industrial design consulting company.",
"Due to the incompatibility between my work profile and the company needs, my collaboration with CANALES CORPORATIVOS stops.",
"2013 starts with a new project as freelance: <b><a href='http://www.accidente.pro' target='_blank'>Accidente.pro</a></b>. A community of professionals which helps car accidents victims.",
"I publish my first android application: <b><a href='https://play.google.com/store/apps/details?id=pro.adtech.projects.plus112.activities'>112 Plus</a></b>. An app to connect with 112 emergency service.",
"I start to work for EMERGIA group as backend developer with <b>Ruby on Rails</b>.",
"In collaboration with the journalist Patricia Ruiz Machí, I publish, for a group of joung directors <b><a href='http://totsaunaveu.es' target='_blank'>Totsaunaveu</a></b>.",
"I publish a new project as freelance: <b><a href='http://www.frutasgrande.com' target='_blank'>Frutas grande</a></b>. A corporative webpage for a fruit wholesaler.",
"My year working for EMERGIA ends."
];
$(function() {
		$( "#slider" ).slider({
			value:2014,
			min: 2001,
			max: 2014,
			step: 1,
			slide: function( event, ui ) {
				$( "#year" ).val(ui.value);
        changeyear(ui.value);
			}
		});
		$( "#year" ).val( $( "#slider" ).slider( "value" ) );
    changeyear($("#slider").slider("value"));
	});
function changeyear(val){
  $(".anno").css("display","none");
  $("#"+val).css("display","block");
  $('#evento').fadeOut('400',function (){$('#evento').html("")});
}
function testo(i){
    $('#evento').fadeOut('400',function (){$('#evento').html(testi[i]);$('#evento').fadeIn('400');});
}
	