
var testi =["Dopo quasi due anni, lascio il mio lavoro di pizzaiolo per dedicarmi allo studio",
  "Primo giorno di universitá nella facoltá di 'Comunicazione Digitale'",
  "Il mio primo viaggio da solo: giro d'Italia in treno<br/>In questo viaggio ritroveró degli amici che vivono a Bergamo, Venezia e Roma",
  "Finalmente ricevo l'esonero dal servizio militare.<br/>Decido che a settembre cominceró l'universitá.",
  "Lavoro come 'Glass collector' in un pub alla periferia di Londra, vicino a dove vivevo.",
  "Concludo il primo anno di universitá superando 6 degli 8 esami previsti<br/><br/>Ottengo la certificazione FSE Microsoft 2000 server in un corso patrocinato dal Fondo Sociale Europeo.",
  "Il mio primo viaggio in aereo. Destinazione: Londra!<br/> Decido passare l'estate nella capitale del Regno Unito per lavorare e migliorare il mio livello di inglese.",
  "Pochi giorni dopo essere tornato da Londra si presenta l'occasione di un fine settimana lungo ad Amsterdam.",
  "Secondo giro d'Italia in treno.<br/>Questa volta il mio tour toccherá le cittá di Roma, Palermo, Agrigento,Molinara (Benevento),Torino.<br/>Lungo il viaggio ritroveró alcuni amici conosciuti poco tempo prima a Londra.",
  "Supero l'esame di scuola guida",
  "Lavoro come cuoco in un locale di Milano preparando aperitivi e panini per l'Happy hour",
  "Frequento un corso serale di formazione CISCO, di sei mesi. Alla sua conclusione ricevo il CCNA (Cisco Certified Networking Associated)",
  "Certificazione FSE Flash Mx<br/><br/>Certificazione FSE Sound Forge 6.0",
  "Certificazione FSE Photoshop 7.0",
  "Certificazione FSE Illustrator 10",
  "Certificazione FSE Maya 5.0<br/><br/>30/05 - Ricevo la borsa di studio Erasmus per un semestre al BTU di Cottbus (Germania)",
  "Visito San Sebastian durante la semana granda.",
  "02/10 - Viaggio di sola andata con destinazione Cottbus",
  "Volo di ritorno in Italia per le festivitá natalizie",
  "Conosco Carmen, pochi giorni dopo, il 29/05, cominceremo a stare insieme.",
  "Carmen torna inItalia dopo aver passato l'estate in Spagna con la sua famiglia<br/>Nonostante tutte le previsioni continuiamo a stare insieme.",
  "Trovo lavoro come gestorie della: 'Piadineria la Caveja' accanto all'Universitá Cattolica di Milano. Il piadinaro sará il mio lavoro fino all'estate 2006",
  "Prima di tornare in Germania, subito dopo le festivitá natalizie, volo per la prima volta verso la Spagna, a Valencia.",
  "Da Berlino vado una settimana a Valencia per vedere 'las Fallas'.<br/><br/>Volo di ritorno da Berlino a Milano. Il mio Erasmus si è concluso.",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Mxp - Vlc a/r",
  "Io e Carmen affittiamo una casa per un mese nel centro storico di Valencia.<br/>È la nostra prima convivenza.",
  "La piadineria chiude per il periodo estivo",
  "Ritorno al lavoro",
  "Volo di andata per Valencia",
  "Io e Carmen partiamo per il nostro primo viaggio insieme.<br/>In autobus attraverseremo la Spagna, andando a trovare vari amici sparsi per il paese.In 15 giorni visiteremo: Valladolid,La Coruña, Santiago de Compostela e Salamanca",
  "Volo di ritorno per l'Italia",
  "Como l'anno precendente Io e Carmen affittiamo una casa a Valencia per passare l'estate insieme.",
  "Io e Carmen festeggiamo il nostro primo capodanno insieme, a Como.",
  "Dopo due anni da gestore lascio il lavoro alla piadineria per dedicarmi alla tesi universitaria",
  "Laurea in 'Comunicacione Digitale'",
  "Corso di formazione su: <br/>Tecnologia COM: VB6.0, ADO, ASP, Sql.<br/>Tecnologia .NET 2.0: C#2.0, VisualStudio 2005, ADO.NET, ASPX. (300h)",
  "MXP - VLC a/r: Albarracín?",
  "Una settimana prima della consegna delle lauree vado a trovare Carmen che si trova a Stoccolma per lavoro.<br/>Il giorno dopo la consegna delle lauree parto per un weekend ad Amsterdam con i miei amici per festeggiare la conclusione di un capitolo importante della mia vita.",
  "Torno in Svezia per stare con Carmen. Insieme visiteremo Stoccolma e Linköping.",
  "Volo di ritorno da Stoccolma",
  "Vincitore del concorso per lo sviluppo di un portale di servizi per la terza etá convocato dalla fondazione 'Ferrario' di Vanzago.",
  "Festeggio il capodanno insieme a Carmen e i miei amici a Milano",
  "Comincio a lavorare per Nexus Advanced Tecnologies.<br/>Inizialmente come sviluppatore interno e successivamente come consulente di sviluppo web allocato presso la banca Fineco di Milano.",
  "Il mio primo progetto da freelancer: Omniamarmi. Una pagina web per un artigiano del marmo.",
  "Secondo lavoro da freelancer: Gilgamesh lounge bar.",
  "Conclusione del corso in tecnologie COM y .NET. <br/>Tra gli alunni, 4 di noi saranno assunti da un azienda di sviluppo software chiamata Nexus Advanced Technologies.",
  "MXP - VLC a/r",
  "MXP - VLC a/r",
  "Accompagno Carmen per un ciclo di conferenze a Norköping (Svezia) riguardanti il progetto che portó avanti l'anno precedente.",
  "MXP - VLC a/r 2x",
  "MXP - VLC a/r 2x",
  "Io e Carmen, per la prima volta, possiamo visitare il cantiere dove sorgerá la nostra nuova futura casa.",
  "Capodanno a Milano, Carmen ed io.",
  "Terzo incarico da freelancer. Excalibur: sito web e forum per un negozio di modellismo di giochi di ruolo.",
  "Quarto incarico da freelancer. Sito web per il ristorante 'Rebelot'",
  "Lascio il mio lavoro in Nexus",
  "La mia prima esperienza di lavoro in Spagna. Sviluppatore web per uno studio di Manises: Alerce",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "MXP  - VLC a/r",
  "Viaggio di sola andata per Valencia",
  "VLC - MXP a/r",
  "VLC - MXP a/r",
  "Viaggio a Milano per passare le festivitá natalizie con la mia famiglia insieme a Carmen",
  "19 AGOSTO - Dopo 5 anni a distanza, é finalmente arrivato il momento di lasciare l'Italia e andare a vivere insieme a Carmen a Valencia.",
  "Capodanno in Italia",
  "Lascio il mio lavoro in Alerce per un altro studio di sviluppo web: Aitana multimedia",
  "Corso di aggiornamento sulla versione 3.5 del framework .NET.",
  "Viaggio in Italia",
  "Viaggio in Italia",
  "Viaggio in Italia",
  "Finesettimana di vacanza a Francoforte",
  "Viaggio in Italia",
  "30 dicembre - Compro la mia prima automobile: una Ford Fiesta di seconda mano.",
  "A causa della crisi lo studio dove lavoro è costretto a operare tagli al personale e, per questo, perdo il mio posto di lavoro.",
  "L'istituto tecnologico del legno, mobile e imballaggio di Paterna mi offre una collaborazione per sviluppare i contenuti web dell'aula virtuale",
  "13 Aprile - Assunzione a tempo indeterminato come programmatore junior presso ZED WORLDWIDE",
  "A causa di un progetto europeo Carmen deve andare alcuni giorni in Finlandia. Vado con lei e insieme visiteremo Helsinki",
  "Come regalo di compleanno, complottando col suo fidanzato, regalo a mia sorella un viaggio per la Romania, Visiteremo insieme il castello di Bran",
  "Italia",
  "Praga",
  "La gioielleria 'De la Concepción' di Valencia, realizza, seguendo un modello da me disegnato, il mio anello di fidanzamento.",
  "12 ottobre - A Praga, durante il tramonto, sulla riva del fiume Moldava chiedo a Carmen di sposarmi.",
  "Accompagno Carmen a Milano per la fiera del mobile.",
  "Italia per il matrimonio di un amico.",
  "Settimana di vacanza in Scozia",
  "19 novembre - Io e Carmen, dopo 8 anni di fidanzamento, ci sposeremo.",
  "Viaggio di nozze in Australia",
  "Weekend lungo in Andalucía, io e Carmen visitiamo Malaga e Granada.",
  "Dimetto da ZED WORLDWIDE per participare alla creazione di JUGO: una startup dell'azienda CANALES CORPORATIVOS",
  "Nuovo progetto come freelancer: web corporativa di <b><a href='http://www.madeinnovation.es' target='_blank'>Madeinnovation</a></b> : uno studio consulenza per la gestione di progetti di disegno industriale.",
  "A causa dell'incompatibilitá tra il mio profilo professionale e le necessitá dell'azienda, la mia collaborazione con CANALES CORPORATIVOS si conclude."
];
$(function() {
		$( "#slider" ).slider({
			value:2012,
			min: 2001,
			max: 2012,
			step: 1,
			slide: function( event, ui ) {
				$( "#year" ).val(ui.value);
        changeyear(ui.value);
			}
		});
		$( "#year" ).val( $( "#slider" ).slider( "value" ) );
    changeyear($("#slider").slider("value"));
	});
function changeyear(val){
  $(".anno").css("display","none");
  $("#"+val).css("display","block");
  $('#evento').fadeOut('400',function (){$('#evento').html("")});
}
function testo(i){
    $('#evento').fadeOut('400',function (){$('#evento').html(testi[i]);$('#evento').fadeIn('400');});
}